// Image service – uses pre-cached logo map + player photo map + TheSportsDB fallback

import teamLogos from '@/data/team_logos.json'
import playerPhotos from '@/data/player_photos.json'
import playerPhotosEra from '@/data/player_photos_era.json'
import { buildPlayerNameVariants } from '@/lib/playerNames'
import { normalizeTeamName } from '@/lib/teamNames'

const THESPORTSDB_API_KEY = '123'
const THESPORTSDB_BASE_URL = 'https://www.thesportsdb.com/api/v1/json'

/**
 * Pre-cached team logo URLs (generated by scripts/fetch_team_logos.js).
 * Covers all 130 teams in the dataset — no live API calls needed for logos.
 */
const STATIC_LOGO_MAP: Record<string, string> = teamLogos as Record<string, string>

/**
 * Era faces (~FIFA 22 / 2021–22 look) for top-100 shot-map players.
 * Preferred over live/current cutouts so the archive matches the 2022 season.
 */
const ERA_PLAYER_PHOTO_MAP: Record<string, string> =
  ((playerPhotosEra as { photos?: Record<string, string> }).photos || {}) as Record<
    string,
    string
  >

/**
 * Pre-cached player photo URLs (generated by scripts/fetch_player_photos.js).
 * Covers all WC players + key Stars-of-the-ERA players.
 */
const STATIC_PLAYER_PHOTO_MAP: Record<string, string> = playerPhotos as Record<string, string>

/**
 * Maps abbreviated / dataset team names → TheSportsDB-compatible names.
 * Used only for player photo fallback lookups.
 */
const TEAM_NAME_MAP: Record<string, string> = {
  // La Liga
  'Ath Madrid': 'Atletico Madrid',
  'Ath Bilbao': 'Athletic Bilbao',
  'Celta': 'Celta Vigo',
  'Espanol': 'Espanyol',
  'Vallecano': 'Rayo Vallecano',
  // Serie A
  'Inter': 'Inter Milan',
  'Verona': 'Hellas Verona',
  // Ligue 1
  'Clermont': 'Clermont Foot',
  // Bundesliga
  "M'gladbach": 'Borussia Monchengladbach',
  'Leverkusen': 'Bayer Leverkusen',
  'Heidenheim': '1. FC Heidenheim',
  'Ein Frankfurt': 'Eintracht Frankfurt',
  // Premier League
  "Nott'm Forest": 'Nottingham Forest',
  'Man United': 'Manchester United',
  'Man City': 'Manchester City',
  'Wolves': 'Wolverhampton Wanderers',
  'Leeds': 'Leeds United',
  'Newcastle': 'Newcastle United',
  'Brighton': 'Brighton and Hove Albion',
  'West Ham': 'West Ham United',
  // World Cup national teams
  'IR Iran': 'Iran',
  'Korea Republic': 'South Korea',
  'United States': 'USA',
}

interface CacheEntry {
  url: string
  timestamp: number
}

/** Small helper: wait ms milliseconds */
const delay = (ms: number) => new Promise((r) => setTimeout(r, ms))

class ImageService {
  private cache: Map<string, CacheEntry> = new Map()
  private readonly CACHE_DURATION = 24 * 60 * 60 * 1000 // 24 hours
  private readonly MISS_CACHE_DURATION = 5 * 60 * 1000  // 5 minutes for failed lookups

  public defaultTeamLogo = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"%3E%3Crect fill="%23ddd" width="100" height="100"/%3E%3Ctext x="50" y="50" text-anchor="middle" dy=".3em" font-size="40" font-weight="bold" fill="%23999"%3E⚽%3C/text%3E%3C/svg%3E'

  public defaultPlayerPhoto = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"%3E%3Crect fill="%23ddd" width="100" height="100"/%3E%3Ccircle cx="50" cy="35" r="15" fill="%23999"/%3E%3Cpath d="M 30 60 Q 30 50 50 50 Q 70 50 70 60 L 70 85 L 30 85 Z" fill="%23999"/%3E%3C/svg%3E'

  /**
   * Get team logo from pre-cached static map.
   * No API calls — instant, no rate limits.
   */
  async fetchTeamLogoByName(teamName: string): Promise<string> {
    const key = normalizeTeamName(teamName) || teamName
    return (
      STATIC_LOGO_MAP[key] ||
      STATIC_LOGO_MAP[teamName] ||
      this.defaultTeamLogo
    )
  }

  /**
   * Get logos for many teams (instant from static map).
   */
  async fetchTeamLogosBatch(
    teamNames: string[],
  ): Promise<Map<string, string>> {
    const result = new Map<string, string>()
    teamNames.forEach((name) => {
      const key = normalizeTeamName(name) || name
      result.set(name, STATIC_LOGO_MAP[key] || STATIC_LOGO_MAP[name] || this.defaultTeamLogo)
    })
    return result
  }

  /**
   * Fetch player data from TheSportsDB by player name
   * Returns the player photo URL
   * Checks pre-cached static map first, then applies name normalization
   * and queries TheSportsDB as fallback.
   */
  async fetchPlayerPhotoByName(playerName: string): Promise<string> {
    const cacheKey = `player-name-${playerName}`

    // 1. Check runtime cache first
    if (this.cache.has(cacheKey)) {
      const cached = this.cache.get(cacheKey)!
      const maxAge = cached.url === this.defaultPlayerPhoto
        ? this.MISS_CACHE_DURATION
        : this.CACHE_DURATION
      if (Date.now() - cached.timestamp < maxAge) {
        return cached.url
      }
      this.cache.delete(cacheKey)
    }

    // 2. Prefer era (~2021–22) faces for top players, then static map, then live API
    //    (e.g. "Lionel Andrés Messi Cuccittini" → "Lionel Messi")
    const namesToTry = buildPlayerNameVariants(playerName)

    for (const name of namesToTry) {
      const eraUrl = ERA_PLAYER_PHOTO_MAP[name]
      // Prefer SoFIFA face cutouts only — skip Wikimedia match stills if any sneak in
      if (eraUrl && /cdn\.sofifa\.(net|com)/i.test(eraUrl)) {
        this.cache.set(cacheKey, { url: eraUrl, timestamp: Date.now() })
        return eraUrl
      }
    }

    for (const name of namesToTry) {
      if (STATIC_PLAYER_PHOTO_MAP[name]) {
        const url = STATIC_PLAYER_PHOTO_MAP[name]
        this.cache.set(cacheKey, { url, timestamp: Date.now() })
        return url
      }
    }

    for (const name of namesToTry) {
      try {
        const response = await fetch(
          `${THESPORTSDB_BASE_URL}/${THESPORTSDB_API_KEY}/searchplayers.php?p=${encodeURIComponent(name)}`,
          { signal: AbortSignal.timeout(5000) }
        )

        if (!response.ok) continue

        const data = await response.json()

        if (data.player && data.player.length > 0) {
          // Prefer footballers when API returns multiple people
          const footballer =
            data.player.find(
              (p: { strSport?: string; strCutout?: string; strThumb?: string }) =>
                (!p.strSport || /soccer|football/i.test(p.strSport)) &&
                (p.strCutout || p.strThumb)
            ) ?? data.player[0]

          const photoUrl = footballer.strCutout || footballer.strThumb
          if (photoUrl) {
            this.cache.set(cacheKey, { url: photoUrl, timestamp: Date.now() })
            return photoUrl
          }
        }
      } catch {
        // Network / timeout / JSON-parse error – try next variant
      }
    }

    // Cache the miss for a SHORT duration so we can retry soon
    this.cache.set(cacheKey, { url: this.defaultPlayerPhoto, timestamp: Date.now() })
    return this.defaultPlayerPhoto
  }

  /**
   * Get a team logo URL (use provided URL or fetch from API if needed)
   * Falls back to default SVG if image is not available
   */
  getTeamLogo(teamId: string, logoUrl?: string): string {
    if (!logoUrl) {
      return this.defaultTeamLogo
    }

    const cacheKey = `team-${teamId}`

    // Check cache
    if (this.cache.has(cacheKey)) {
      const cached = this.cache.get(cacheKey)!
      if (Date.now() - cached.timestamp < this.CACHE_DURATION) {
        return cached.url
      }
      this.cache.delete(cacheKey)
    }

    // Cache the URL
    this.cache.set(cacheKey, {
      url: logoUrl,
      timestamp: Date.now(),
    })

    return logoUrl
  }

  /**
   * Get a player photo URL (use provided URL or fetch from API if needed)
   * Falls back to default SVG if image is not available
   */
  getPlayerPhoto(playerId: string, photoUrl?: string): string {
    if (!photoUrl) {
      return this.defaultPlayerPhoto
    }

    const cacheKey = `player-${playerId}`

    // Check cache
    if (this.cache.has(cacheKey)) {
      const cached = this.cache.get(cacheKey)!
      if (Date.now() - cached.timestamp < this.CACHE_DURATION) {
        return cached.url
      }
      this.cache.delete(cacheKey)
    }

    // Cache the URL
    this.cache.set(cacheKey, {
      url: photoUrl,
      timestamp: Date.now(),
    })

    return photoUrl
  }

  /**
   * Clear all cached images (for testing or manual cache clearing)
   */
  clearCache(): void {
    this.cache.clear()
  }

  /**
   * Get cache statistics
   */
  getCacheStats(): { size: number; entries: string[] } {
    return {
      size: this.cache.size,
      entries: Array.from(this.cache.keys()),
    }
  }
}

// Export singleton instance
export const imageService = new ImageService()
