/**
 * Normalize Understat / long club names → dataset team names (team_logos / teams.json).
 */

const TO_DATASET: Record<string, string> = {
  'AC Milan': 'Milan',
  Milan: 'Milan',
  'Inter Milan': 'Inter',
  Inter: 'Inter',
  'Athletic Club': 'Ath Bilbao',
  'Athletic Bilbao': 'Ath Bilbao',
  'Atletico Madrid': 'Ath Madrid',
  'Atlético Madrid': 'Ath Madrid',
  'Atlético de Madrid': 'Ath Madrid',
  'Bayer Leverkusen': 'Leverkusen',
  'Bayer 04 Leverkusen': 'Leverkusen',
  Leverkusen: 'Leverkusen',
  'Borussia Dortmund': 'Dortmund',
  Dortmund: 'Dortmund',
  'Borussia M.Gladbach': "M'gladbach",
  'Borussia Monchengladbach': "M'gladbach",
  "Borussia M'gladbach": "M'gladbach",
  "M'gladbach": "M'gladbach",
  'Celta Vigo': 'Celta',
  Celta: 'Celta',
  'Clermont Foot': 'Clermont',
  Clermont: 'Clermont',
  'Eintracht Frankfurt': 'Ein Frankfurt',
  'Ein Frankfurt': 'Ein Frankfurt',
  Espanyol: 'Espanol',
  Espanol: 'Espanol',
  'FC Cologne': 'FC Koln',
  'FC Koln': 'FC Koln',
  '1. FC Koln': 'FC Koln',
  'Mainz 05': 'Mainz',
  Mainz: 'Mainz',
  'Manchester City': 'Man City',
  'Man City': 'Man City',
  'Manchester United': 'Man United',
  'Man United': 'Man United',
  'Man Utd': 'Man United',
  'Newcastle United': 'Newcastle',
  Newcastle: 'Newcastle',
  'Nottingham Forest': "Nott'm Forest",
  "Nott'm Forest": "Nott'm Forest",
  'Paris Saint Germain': 'Paris SG',
  'Paris Saint-Germain': 'Paris SG',
  'Paris S-G': 'Paris SG',
  'Paris SG': 'Paris SG',
  PSG: 'Paris SG',
  'RasenBallsport Leipzig': 'RB Leipzig',
  'RB Leipzig': 'RB Leipzig',
  'Rayo Vallecano': 'Vallecano',
  Vallecano: 'Vallecano',
  'Real Betis': 'Betis',
  Betis: 'Betis',
  'Real Sociedad': 'Sociedad',
  Sociedad: 'Sociedad',
  'Real Valladolid': 'Valladolid',
  Valladolid: 'Valladolid',
  'VfB Stuttgart': 'Stuttgart',
  Stuttgart: 'Stuttgart',
  'Wolverhampton Wanderers': 'Wolves',
  Wolves: 'Wolves',
  'Hertha Berlin': 'Hertha',
  Hertha: 'Hertha',
  'Schalke 04': 'Schalke 04',
  'Hamburger SV': 'Hamburg',
  'Hannover 96': 'Hannover',
  'Saint-Etienne': 'Saint-Etienne',
  'SC Bastia': 'Bastia',
  'Deportivo La Coruna': 'Deportivo',
  Brighton: 'Brighton',
  'Brighton and Hove Albion': 'Brighton',
  'West Ham': 'West Ham',
  'West Ham United': 'West Ham',
  'Leeds United': 'Leeds',
  Leeds: 'Leeds',
  'Tottenham Hotspur': 'Tottenham',
  Tottenham: 'Tottenham',
  Spurs: 'Tottenham',
  'Bayern Munich': 'Bayern Munich',
  Bayern: 'Bayern Munich',
  'FC Bayern Munich': 'Bayern Munich',
  'Hellas Verona': 'Verona',
  Verona: 'Verona',
  '1. FC Heidenheim': 'Heidenheim',
  Heidenheim: 'Heidenheim',
  'Union Berlin': 'Union Berlin',
  'Werder Bremen': 'Werder Bremen',
  'Hoffenheim': 'Hoffenheim',
  'TSG Hoffenheim': 'Hoffenheim',
  Freiburg: 'Freiburg',
  'SC Freiburg': 'Freiburg',
  Augsburg: 'Augsburg',
  Bochum: 'Bochum',
  'Vfl Bochum': 'Bochum',
  Monaco: 'Monaco',
  Nice: 'Nice',
  Lille: 'Lille',
  Lyon: 'Lyon',
  Marseille: 'Marseille',
  Nantes: 'Nantes',
  Rennes: 'Rennes',
  Reims: 'Reims',
  Lorient: 'Lorient',
  Toulouse: 'Toulouse',
  Strasbourg: 'Strasbourg',
  Montpellier: 'Montpellier',
  Troyes: 'Troyes',
  Ajaccio: 'Ajaccio',
  Auxerre: 'Auxerre',
  Brest: 'Brest',
  Angers: 'Angers',
  'Genoa': 'Genoa',
  Benevento: 'Benevento',
  Salernitana: 'Salernitana',
  Spezia: 'Spezia',
  Sampdoria: 'Sampdoria',
  Torino: 'Torino',
  Udinese: 'Udinese',
  Sassuolo: 'Sassuolo',
  Monza: 'Monza',
  Lecce: 'Lecce',
  Cremonese: 'Cremonese',
  Empoli: 'Empoli',
  Fiorentina: 'Fiorentina',
  Napoli: 'Napoli',
  Roma: 'Roma',
  Lazio: 'Lazio',
  Juventus: 'Juventus',
  Atalanta: 'Atalanta',
  Bologna: 'Bologna',
  Barcelona: 'Barcelona',
  'Real Madrid': 'Real Madrid',
  Sevilla: 'Sevilla',
  Valencia: 'Valencia',
  Villarreal: 'Villarreal',
  Getafe: 'Getafe',
  Osasuna: 'Osasuna',
  Mallorca: 'Mallorca',
  Girona: 'Girona',
  Cadiz: 'Cadiz',
  Almeria: 'Almeria',
  Elche: 'Elche',
  Arsenal: 'Arsenal',
  Chelsea: 'Chelsea',
  Liverpool: 'Liverpool',
  Everton: 'Everton',
  Fulham: 'Fulham',
  'Crystal Palace': 'Crystal Palace',
  Southampton: 'Southampton',
  'Aston Villa': 'Aston Villa',
  Brentford: 'Brentford',
  Bournemouth: 'Bournemouth',
  Leicester: 'Leicester',
  'Leicester City': 'Leicester',
}

/** First club if Understat joined "A,B" dirty titles. */
export function primaryClubName(raw: string): string {
  const first = String(raw || '')
    .split(',')[0]
    .trim()
  return first
}

/** Map any club/nation label to the dataset/logo key when possible. */
export function normalizeTeamName(raw: string | null | undefined): string {
  if (!raw) return ''
  const primary = primaryClubName(raw)
  if (TO_DATASET[primary]) return TO_DATASET[primary]
  // Accent-insensitive pass
  const stripped = primary.normalize('NFD').replace(/[\u0300-\u036f]/g, '')
  if (TO_DATASET[stripped]) return TO_DATASET[stripped]
  return primary
}
